# Generated by Django 4.1.3 on 2023-01-12 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart_city', models.CharField(help_text='Enter a departure city name', max_length=100, verbose_name='City')),
                ('arrival_city', models.CharField(help_text='Enter an arrival city name', max_length=100, verbose_name='City')),
                ('departure_time', models.TimeField(help_text='Enter departure time')),
                ('arrival_time', models.TimeField(help_text='Enter arrival time')),
                ('price', models.IntegerField(help_text='Enter the price', verbose_name='Price')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('available_seats', models.PositiveIntegerField(unique=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buy_tickets.bustrip')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip', models.CharField(max_length=100)),
                ('departure_date', models.DateField()),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('passenger_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('number_of_seats', models.PositiveIntegerField()),
                ('total_price', models.PositiveIntegerField()),
                ('available_seats', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='buy_tickets.day', to_field='available_seats')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('orders', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buy_tickets.ticket')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
