# Generated by Django 4.1.3 on 2023-01-12 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buy_tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='available_seats',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='available_seats',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buy_tickets.day'),
        ),
    ]
