# Generated by Django 4.1.3 on 2023-01-22 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buy_tickets', '0004_alter_bustrip_arrival_city_alter_bustrip_depart_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='date',
            field=models.DateField(verbose_name='Date of trip'),
        ),
        migrations.AlterField(
            model_name='day',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buy_tickets.bustrip', verbose_name='Your trip'),
        ),
    ]
